### PR TITLE
Add generation and upload of master index.html for repository.

### PR DESCRIPTION
**Pull request by pdonis**
This addresses issue #18.

### CODE REVIEW

**Comment by natefoo** [comment]
@mdwint @rubenvdb this would be a useful feature (that I just discovered after making [a standalone script](https://gist.github.com/natefoo/9fa69040c13b08e70fa6dbd50d1a3d13) that does the same thing), are you opposed to this or is there anything else you'd like to see (other than fixing the conflicts) to get this merged?

**Comment by mdwint** [comment]
> this would be a useful feature

I don't immediately see the benefit of this feature (but I might be wrong, so please elaborate). Does pip use a top-level index for finding packages? Or would users visit this page to browse the repository and download packages manually?

**Comment by natefoo** [comment]
> Does pip use a top-level index for finding packages?

A quick test suggests that it doesn't, but [PEP 503](https://www.python.org/dev/peps/pep-0503/) specifies:

> Within a repository, the root URL (/) **MUST** be a valid HTML5 page with a single anchor element per project in the repository. The text of the anchor tag **MUST** be the normalized name of the project and the href attribute **MUST** link to the URL for that particular project. As an example:
> ```
> <!DOCTYPE html>
> <html>
>   <body>
>     <a href="/frob/">frob</a>
>     <a href="/spamspamspam/">spamspamspam</a>
>   </body>
> </html>
```

I find it useful for verifying that things are where I expect them and for people to quickly/easily discover what packages are available on our server when determining whether a new package needs to be added, but I admit that's just a convenience for humans.

**Comment by louis-jaris** [comment]
Maybe this feature can be disabled by default and make it activable through a command-line argument. This will remove the possible concurrent pushes of PyPI packages on S3.
This could be periodically executed to refresh the top-level index.

**Comment by natefoo** [comment]
FWIW I spun my work in to a package [here](https://github.com/natefoo/s3pypi-root-index) that you can use until something is implemented directly in s3pypi.

**Comment by etiennebrateau** [comment]
Can you change the behavior in case of secret? The place where index should be changed and the paths of libraries should be relative of the index.hml location

**Pull request closed without merging**
