### PR TITLE
Support --dist-path with only a wheel package present.

### PR DESCRIPTION
**Pull request by takacsd**
Right now we generate sdist package even when "--no-sdist" parameter is present just for the sake of getting the package name from the stdout. We can use "setup.py --fullname" for that.

Also, currently the "--dist-path" option only gets the package name from the sdist filename.
In case of the wheel package we can not use the filename because some characters gets converted to underscore, so we need to read the METADATA from the package itself.

### CODE REVIEW

**Comment by mdwint** [comment]
Thanks for contributing! I have two remarks before we can merge this:

- [ ] The integration tests fail on Python 2 (you can run them with `tox`)
- [ ] Please run `make format` to fix formatting

**Comment by takacsd** [comment]
@mdwint Done.

**Comment by mdwint** [comment]
Thanks! This is now available in release 0.10.0.

**Comment by takacsd** [comment]
Cool, I didn't expect to be able to use it right away, thanks!

**Pull request merged**
